// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VueSneakers.API.Models;

#nullable disable

namespace VueSneakers.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240408202510_AddedCorectVersionOfTheItemEntity")]
    partial class AddedCorectVersionOfTheItemEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VueSneakers.API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            ImageUrl = "/sneakers/sneakers-1.jpg",
                            Price = 123m,
                            Title = "Мужские Кроссовки Nike Blazer Mid Suede"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/sneakers/sneakers-2.jpg",
                            Price = 123m,
                            Title = "Мужские Кроссовки Nike Blazer Mid Suede"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/sneakers/sneakers-3.jpg",
                            Price = 123m,
                            Title = "Мужские Кроссовки Nike Blazer Mid Suede"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/sneakers/sneakers-4.jpg",
                            Price = 123m,
                            Title = "Мужские Кроссовки Nike Blazer Mid Suede"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/sneakers/sneakers-5.jpg",
                            Price = 123m,
                            Title = "Мужские Кроссовки Nike Blazer Mid Suede"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/sneakers/sneakers-6.jpg",
                            Price = 123m,
                            Title = "Мужские Кроссовки Nike Blazer Mid Suede"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
